title: Siva's Blog
description: >
  My Experiments.
url: "/"
paginate:	5 # The number of posts to show per page on your homepage
name: "Sivarama Krishnan"
email:
markdown: kramdown
twitter_username: meredilettante
twitter_image: 
permalink: none
kramdown:
  parse_block_html: true
plugins: [jekyll-paginate]
gems:
  - jekyll-paginate
  - jekyll-compose
  - jekyll-sass-converter
  - jekyll-textile-converter
long_description: >
  I write about AI/ML, Science, Math and occasionally about philosophy.
real_url: https://siva.github.io